In [2]:
import numpy as np


In [3]:
v = np.arange(9).reshape(3,3)

print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
tri = np.triu(v)
print(tri)

[[0 1 2]
 [0 4 5]
 [0 0 8]]


In [5]:
revers = np.tril(tri)    
print(revers)

[[0 0 0]
 [0 4 0]
 [0 0 8]]


In [6]:
A = np.array([ [4,5,1],[0,1,11],[4,9,7] ])
print(A)

[[ 4  5  1]
 [ 0  1 11]
 [ 4  9  7]]


In [7]:
print(A + 2*np.eye(len(A)))


[[ 6.  5.  1.]
 [ 0.  3. 11.]
 [ 4.  9.  9.]]


In [8]:
print(np.multiply(2,A))


[[ 8 10  2]
 [ 0  2 22]
 [ 8 18 14]]


In [9]:
print((A*2))

[[ 8 10  2]
 [ 0  2 22]
 [ 8 18 14]]


In [10]:
c = np.array([[1,2,3],[3,2,1]])
d = np.array([[1,2],[2,3],[3,1]])