In [1]:
import numpy as np

In [2]:
a = np.array([3,0,6])
b = np.array([1,2,5])

l1 =4 
l2 = 3


print(l1*a+l2*b)

[15  6 39]


In [7]:
g = np.array([4,3]).transpose()
print(g)


[4 3]


In [12]:
gg = np.array([[3,0,6],[1,2,5]]).T
print(gg)

[[3 1]
 [0 2]
 [6 5]]


In [14]:
print(gg@g)

[15  6 39]
