In [1]:
import numpy as np

In [2]:
A = np.array([(2,3,0),(-1,1,1),(2,0,1)])
B = np.array([(1,2,1),(-1,1,2),(1,0,1)])
I = np.eye(3)
X = np.array([1,2,-1])


print("A+B\n", A+B)

print("A.I3\n",np.dot(A,I))

print("I3.A\n",np.dot(I,A))

print("A.B\n",np.dot(A,B))
print("B.A\n",np.dot(B,A))

print("A.A\n",np.dot(A,A))
print("A.X\n",np.dot(A,X))


A+B
 [[ 3  5  1]
 [-2  2  3]
 [ 3  0  2]]
A.I3
 [[ 2.  3.  0.]
 [-1.  1.  1.]
 [ 2.  0.  1.]]
I3.A
 [[ 2.  3.  0.]
 [-1.  1.  1.]
 [ 2.  0.  1.]]
A.B
 [[-1  7  8]
 [-1 -1  2]
 [ 3  4  3]]
B.A
 [[ 2  5  3]
 [ 1 -2  3]
 [ 4  3  1]]
A.A
 [[ 1  9  3]
 [-1 -2  2]
 [ 6  6  1]]
A.X
 [8 0 1]


In [3]:
#exercise 2

In [4]:
"""A = np.array([(5,2),(1,0)])

print(np.linalg.inv(A))

A = np.array([(1,1),(1,1)])
#print(np.linalg.inv(A))
print("det")
print(np.linalg.det(A))
#singular means that either we have many answers or zero answers in linea combinations
print("---")"""
A = np.array([(-1,0),(2,3)])
print(np.linalg.det(A))
print(A)
A = np.array([(-1,0),(2,3)])
print(np.linalg.inv(A))
print(np.linalg.det(A))




-2.9999999999999996
[[-1  0]
 [ 2  3]]
[[-1.00000000e+00  2.77555756e-17]
 [ 6.66666667e-01  3.33333333e-01]]
-2.9999999999999996


In [5]:
#exercise three
D =  np.array([(2,0,0),(0,-3,0),(0,0,4)])

print(np.dot(D,D))
z = np.dot(D,D)
print(np.dot(z,D))

print(np)

[[ 4  0  0]
 [ 0  9  0]
 [ 0  0 16]]
[[  8   0   0]
 [  0 -27   0]
 [  0   0  64]]
<module 'numpy' from '/home/lytoe/miniconda3/lib/python3.14/site-packages/numpy/__init__.py'>


In [6]:
A =  np.array([(5,1),(3,3)])
print(np.dot(A,A))

[[28  8]
 [24 12]]


In [7]:
I = np.eye(2)
print((8 * A) - (12 * I))
print("Det A ",np.linalg.det(A))

[[28.  8.]
 [24. 12.]]
Det A  11.999999999999995


In [8]:
#Exercise 1


A = np.array([(1,2,-1,1),(3,-4,0,2),(2,2,-3,2),(-2,6,-1,-1)])

print(np.linalg.det(A))

-2.3473286806360373e-15


In [15]:
# exercise 2 
v1 = np.array([(2,8,1),(3,5,0),(3,2,5)])
fe1 = np.array([1,1,3])
fe2 = np.array([1,0,4])
fe3 = np.array([0,2,1])

fe1_e = 1e1 + 1e2 + 3e3
fe2_e = 1e1 + 0e2 + 4e3
fe3_e = 0e1 + 2e2 + 1e3
# so here we read the coefficients horizentally, but we write them as a matrix in column order(just the rule)
M = np.array([(1,1,0),(1,0,2),(3,4,1)])

#new basis
v1 = np.array([2,3,3])
v2 = np.array([8,5,2])
v3 = np.array([1,0,5])
stacked_v = np.column_stack((v1,v2,v3))
print(stacked_v)

inverted_v = np.linalg.inv(stacked_v)
new_matrix = np.matmul(stacked_v,M,inverted_v)
new_matrix_2 = stacked_v @ M @ inverted_v
print("new matrix2 with new basis =>\n",new_matrix_2)
print("new matrix with new basis =>\n",new_matrix)

[[2 8 1]
 [3 5 0]
 [3 2 5]]
new matrix2 with new basis =>
 [[557. 487. 434.]
 [328. 287. 256.]
 [624. 396. 651.]]
new matrix with new basis =>
 [[13.  6. 17.]
 [ 8.  3. 10.]
 [20. 23.  9.]]


In [10]:
#exercise 3 
"""
by multiplying the A to X, we get the left side of the S linear system, bascially be reconstructed it,

any matrix could be written as a linear equation. to be solved.


"""
l = np.array([(1,0,0),(2,1,0),(4,11/5,1)])
u = np.array([(1,3,4),(0,-5,5),(0,0,-3)])

print(np.dot(l,u))
print("----------------")
print(np.matmul(l,u))
print("----------------")



[[ 1.  3.  4.]
 [ 2.  1. 13.]
 [ 4.  1. 24.]]
----------------
[[ 1.  3.  4.]
 [ 2.  1. 13.]
 [ 4.  1. 24.]]
----------------


In [ ]:
# question 4 Matrix decompositions
A = np.array([(8,6,4,1),(1,4,5,1),(8,4,1,1),(1,4,3,6)])
B = np.array([19,11,14,14])
B_decimal = np.array([19.01,11.05,14.07,14.05])
print(np.linalg.inv(A) @ B)
print("------------------------------------------")
print(np.linalg.inv(A) @ B_decimal)
# the A matrix is "ILL-CONDITIONED" meanning the system is highly sensetive to minor perturbation
# or noise or rounding number, 



[1. 1. 1. 1.]
------------------------------------------
[-2.34   9.745 -4.85  -1.34 ]


In [12]:
A = np.array([(2,0),(0,3)])
B = np.array([1,0])
C = np.array([2,0])
print(np.matmul(A,C))

[4 0]
